---
projectTitle: UKBB_Trait_Analysis
# htmlOutputPath: /s/public_webshare/project/UKBB_Splicing_Analysis/html

gtf_file: "/s/genomes/Gencode/Gencode_human/release_34/gencode.v34.annotation.gtf.gz"
fasta_file: "/s/genomes/Gencode/Gencode_human/release_34/GRCh38.primary_assembly.genome.fa"

protein_coding_genes_csv: "/s/project/rep/processed/trait_associations/protein_coding_genes.hg38.csv"
protein_coding_genes_pq: "/s/project/rep/processed/trait_associations/protein_coding_genes.hg38.parquet"

ukbb_raw_phenotypes_dir: "/s/raw/ukbiobank/phenotypes"
ukbb_processed_phenotypes_dir: "/s/project/uk_biobank/processed/phenotypes"

# input
genebass_results_mt: "/s/project/rep/processed/genebass/results.mt"
# output
genebass_results_pq: "/s/project/rep/processed/genebass/results.parquet"
genebass_results_filtered_pq: "/s/project/rep/processed/genebass/filtered.parquet"
genebass_bonferroni_cutoff: 0.01


trait_associations: "/s/project/rep/processed/trait_associations/associate/{phenotype_col}"
feature_sets_dir: "/s/project/rep/processed/trait_associations/feature_sets"


abexp_predictions: "/s/project/rep/processed/training_results_v10/ukbb_wes_200k/predict_all/fset=DNA_only_nosplice_tl010/gtex_v8_old_dna/dna_only/DNA_only_nosplice_tl010@train_simplecv.py#lightgbm/data.parquet"
vep_predictions: "/s/project/rep/processed/training_results_v10/ukbb_wes_200k/feature_sets/aggregate_vep_spark.py@gt=any_tl=CANONICAL/data.parquet"